"""Static toolbar chrome token presets keyed by theme family."""

from __future__ import annotations

TOOLBAR_PRESETS: dict[str, dict[str, str]] = {
    "light": {
        "toolbar_run_bg": "#E6F4EA",
        "toolbar_run_hover_bg": "#D1EDDA",
        "toolbar_run_pressed_bg": "#B7DFC6",
        "toolbar_run_fg": "#15803D",
        "toolbar_stop_bg": "#FEE2E2",
        "toolbar_stop_hover_bg": "#FECACA",
        "toolbar_stop_pressed_bg": "#FCA5A5",
        "toolbar_stop_fg": "#B91C1C",
        "toolbar_debug_bg": "#FEF3C7",
        "toolbar_debug_hover_bg": "#FDE68A",
        "toolbar_debug_pressed_bg": "#FCD34D",
        "toolbar_debug_fg": "#B45309",
        "toolbar_package_bg": "#E8EEFF",
        "toolbar_package_hover_bg": "#D6E0FF",
        "toolbar_package_pressed_bg": "#C4D4FF",
        "toolbar_package_fg": "#2952CC",
        "chrome_hover_overlay": "rgba(0, 0, 0, 0.08)",
    },
    "dark": {
        "toolbar_run_bg": "#1B3D1B",
        "toolbar_run_hover_bg": "#22502A",
        "toolbar_run_pressed_bg": "#2A6434",
        "toolbar_run_fg": "#4ADE80",
        "toolbar_stop_bg": "#3D1B1B",
        "toolbar_stop_hover_bg": "#502222",
        "toolbar_stop_pressed_bg": "#642A2A",
        "toolbar_stop_fg": "#F87171",
        "toolbar_debug_bg": "#3D2E0A",
        "toolbar_debug_hover_bg": "#50400E",
        "toolbar_debug_pressed_bg": "#645214",
        "toolbar_debug_fg": "#FBBF24",
        "toolbar_package_bg": "#1B2A4A",
        "toolbar_package_hover_bg": "#243758",
        "toolbar_package_pressed_bg": "#2E4468",
        "toolbar_package_fg": "#7EA8FF",
        "chrome_hover_overlay": "rgba(255, 255, 255, 0.1)",
    },
    "hc_light": {
        "toolbar_run_bg": "#E6FFE6",
        "toolbar_run_hover_bg": "#CCFFCC",
        "toolbar_run_pressed_bg": "#B3FFB3",
        "toolbar_run_fg": "#005000",
        "toolbar_stop_bg": "#FFE6E6",
        "toolbar_stop_hover_bg": "#FFCCCC",
        "toolbar_stop_pressed_bg": "#FFB3B3",
        "toolbar_stop_fg": "#9C0000",
        "toolbar_debug_bg": "#FFF8E6",
        "toolbar_debug_hover_bg": "#FFEFCC",
        "toolbar_debug_pressed_bg": "#FFE6B3",
        "toolbar_debug_fg": "#7A4500",
        "toolbar_package_bg": "#E6E6FF",
        "toolbar_package_hover_bg": "#CCCCFF",
        "toolbar_package_pressed_bg": "#B3B3FF",
        "toolbar_package_fg": "#0000C0",
        "chrome_hover_overlay": "rgba(0, 0, 0, 0.12)",
    },
    "hc_dark": {
        "toolbar_run_bg": "#0A2A0A",
        "toolbar_run_hover_bg": "#0F3A0F",
        "toolbar_run_pressed_bg": "#144A14",
        "toolbar_run_fg": "#7FCB66",
        "toolbar_stop_bg": "#2A0A0A",
        "toolbar_stop_hover_bg": "#3A0F0F",
        "toolbar_stop_pressed_bg": "#4A1414",
        "toolbar_stop_fg": "#FF8080",
        "toolbar_debug_bg": "#2A2000",
        "toolbar_debug_hover_bg": "#3A2A00",
        "toolbar_debug_pressed_bg": "#4A3400",
        "toolbar_debug_fg": "#FFD700",
        "toolbar_package_bg": "#0A0A2A",
        "toolbar_package_hover_bg": "#0F0F3A",
        "toolbar_package_pressed_bg": "#14144A",
        "toolbar_package_fg": "#7CB7FF",
        "chrome_hover_overlay": "rgba(255, 255, 255, 0.15)",
    },
}
