(comment) @comment
(marginalia) @comment

(literal) @string

(int) @number

[
 (keyword_select)
 (keyword_from)
 (keyword_where)
 (keyword_insert)
 (keyword_update)
 (keyword_delete)
 (keyword_create)
 (keyword_drop)
 (keyword_alter)
 (keyword_table)
 (keyword_into)
 (keyword_values)
 (keyword_set)
 (keyword_join)
 (keyword_left)
 (keyword_right)
 (keyword_inner)
 (keyword_full)
 (keyword_cross)
 (keyword_natural)
 (keyword_using)
 (keyword_on)
 (keyword_and)
 (keyword_or)
 (keyword_not)
 (keyword_in)
 (keyword_is)
 (keyword_null)
 (keyword_as)
 (keyword_order)
 (keyword_by)
 (keyword_group)
 (keyword_having)
 (keyword_limit)
 (keyword_offset)
 (keyword_distinct)
 (keyword_union)
 (keyword_intersect)
 (keyword_except)
 (keyword_all)
 (keyword_exists)
 (keyword_between)
 (keyword_like)
 (keyword_similar)
 (keyword_case)
 (keyword_when)
 (keyword_then)
 (keyword_else)
 (keyword_end)
 (keyword_begin)
 (keyword_commit)
 (keyword_rollback)
 (keyword_primary)
 (keyword_key)
 (keyword_foreign)
 (keyword_references)
 (keyword_index)
 (keyword_view)
 (keyword_with)
 (keyword_recursive)
 (keyword_window)
 (keyword_over)
 (keyword_partition)
 (keyword_row)
 (keyword_rows)
 (keyword_range)
 (keyword_returning)
 (keyword_materialized)
 (keyword_lateral)
 (keyword_nulls)
 (keyword_first)
 (keyword_last)
 (keyword_if)
 (keyword_cascade)
 (keyword_restrict)
 (keyword_check)
 (keyword_constraint)
 (keyword_unique)
 (keyword_default)
 (keyword_temporary)
 (keyword_temp)
 (keyword_truncate)
 (keyword_conflict)
 (keyword_do)
 (keyword_nothing)
 (keyword_asc)
 (keyword_desc)
 (keyword_replace)
 (keyword_database)
 (keyword_schema)
 (keyword_function)
 (keyword_procedure)
 (keyword_trigger)
] @keyword

[
 (keyword_int)
 (keyword_boolean)
 (keyword_text)
 (keyword_varchar)
 (keyword_numeric)
 (keyword_timestamp)
 (keyword_date)
 (keyword_time)
 (keyword_interval)
 (keyword_jsonb)
 (keyword_json)
 (keyword_decimal)
 (keyword_float)
 (keyword_double)
 (keyword_char)
 (keyword_bigint)
 (keyword_smallint)
 (keyword_serial)
 (keyword_bytea)
 (keyword_uuid)
] @class.def

[
 (keyword_true)
 (keyword_false)
] @number

(invocation (object_reference (identifier) @function.call))
(relation (object_reference (identifier) @class.def))
(field (identifier) @property)
(field (object_reference (identifier) @property))

["=" "<" ">" "<=" ">=" "<>" "!=" "+" "-" "*" "/" "%"] @operator
["(" ")" "[" "]"] @punctuation.bracket
["," "." ";"] @punctuation.delimiter
