"""Shared constants for bootstrap/path contracts."""

APP_RUN_PATH = "/opt/freecad/AppRun"

GLOBAL_STATE_DIRNAME = ".choreboy_code_studio"
GLOBAL_SETTINGS_FILENAME = "settings.json"
GLOBAL_RECENT_PROJECTS_FILENAME = "recent_projects.json"
GLOBAL_LOGS_DIRNAME = "logs"
GLOBAL_CACHE_DIRNAME = "cache"
GLOBAL_CRASH_REPORTS_DIRNAME = "crash_reports"
GLOBAL_STATE_DB_FILENAME = "state.sqlite3"
APP_LOG_FILENAME = "app.log"
APP_LOGGER_NAMESPACE = "choreboy_code_studio"
APP_LOG_FORMAT = "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
APP_LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"
UI_LAYOUT_SETTINGS_KEY = "ui_layout"
UI_IMPORT_UPDATE_POLICY_KEY = "python_import_update_policy"
UI_IMPORT_UPDATE_POLICY_DEFAULT = "ask"
UI_EDITOR_SETTINGS_KEY = "editor"
UI_EDITOR_TAB_WIDTH_KEY = "tab_width"
UI_EDITOR_FONT_SIZE_KEY = "font_size"
UI_EDITOR_TAB_WIDTH_DEFAULT = 4
UI_EDITOR_FONT_SIZE_DEFAULT = 10
UI_INTELLIGENCE_SETTINGS_KEY = "intelligence"
UI_INTELLIGENCE_ENABLE_COMPLETION_KEY = "enable_completion"
UI_INTELLIGENCE_AUTO_TRIGGER_COMPLETION_KEY = "auto_trigger_completion"
UI_INTELLIGENCE_COMPLETION_MIN_CHARS_KEY = "completion_min_chars"
UI_INTELLIGENCE_ENABLE_COMPLETION_DEFAULT = True
UI_INTELLIGENCE_AUTO_TRIGGER_COMPLETION_DEFAULT = True
UI_INTELLIGENCE_COMPLETION_MIN_CHARS_DEFAULT = 2

PROJECT_META_DIRNAME = ".cbcs"
PROJECT_MANIFEST_FILENAME = "project.json"
PROJECT_RUNS_DIRNAME = "runs"
PROJECT_CACHE_DIRNAME = "cache"
PROJECT_LOGS_DIRNAME = "logs"
RUN_MANIFEST_FILENAME_PREFIX = "run_manifest_"
RUN_LOG_FILENAME_PREFIX = "run_"
RUN_LOG_FILENAME_SUFFIX = ".log"
RUN_ID_TIMESTAMP_FORMAT = "%Y%m%d_%H%M%S"
RUN_MANIFEST_VERSION = 1

RUN_EXIT_SUCCESS = 0
RUN_EXIT_USER_CODE_ERROR = 1
RUN_EXIT_BOOTSTRAP_ERROR = 2
RUN_EXIT_INVALID_MANIFEST = 3
RUN_EXIT_SAFE_MODE_BLOCKED = 4
RUN_EXIT_TERMINATED_BY_USER = 130
RUN_MODE_PYTHON_SCRIPT = "python_script"
RUN_MODE_QT_APP = "qt_app"
RUN_MODE_FREECAD_HEADLESS = "freecad_headless"
RUN_MODE_PYTHON_REPL = "python_repl"
RUN_MODE_PYTHON_DEBUG = "python_debug"

TEMP_NAMESPACE_DIRNAME = "choreboy_code_studio"
