"""Shared constants for bootstrap/path contracts."""

APP_VERSION = "0.1"

APP_RUN_PATH = "/opt/freecad/AppRun"

GLOBAL_STATE_DIRNAME = "choreboy_code_studio_state"
GLOBAL_SETTINGS_FILENAME = "settings.json"
GLOBAL_RECENT_PROJECTS_FILENAME = "recent_projects.json"
GLOBAL_PYTHON_CONSOLE_HISTORY_FILENAME = "python_console_history.json"
GLOBAL_LOGS_DIRNAME = "logs"
GLOBAL_CACHE_DIRNAME = "cache"
GLOBAL_CRASH_REPORTS_DIRNAME = "crash_reports"
GLOBAL_TRASH_DIRNAME = "trash"
GLOBAL_TRASH_FILES_DIRNAME = "files"
GLOBAL_TRASH_INFO_DIRNAME = "info"
GLOBAL_STATE_DB_FILENAME = "state.sqlite3"
PLUGINS_STATE_DIRNAME = "plugins"
PLUGINS_INSTALLED_DIRNAME = "installed"
PLUGINS_LOGS_DIRNAME = "logs"
PLUGINS_REGISTRY_FILENAME = "registry.json"
PLUGINS_TRUST_FILENAME = "trust.json"
PLUGIN_REGISTRY_SCHEMA_VERSION = 1
PLUGIN_MANIFEST_FILENAME = "plugin.json"
PLUGIN_PACKAGE_EXTENSION = ".cbcs-plugin.zip"
PLUGIN_API_VERSION = 1
PLUGIN_DISABLE_AFTER_FAILURES_DEFAULT = 3
APP_LOG_FILENAME = "app.log"
APP_LOGGER_NAMESPACE = "choreboy_code_studio"
APP_LOG_FORMAT = "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
APP_LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"
UI_LAYOUT_SETTINGS_KEY = "ui_layout"
UI_IMPORT_UPDATE_POLICY_KEY = "python_import_update_policy"
UI_IMPORT_UPDATE_POLICY_DEFAULT = "ask"
UI_EDITOR_SETTINGS_KEY = "editor"
UI_EDITOR_TAB_WIDTH_KEY = "tab_width"
UI_EDITOR_FONT_SIZE_KEY = "font_size"
UI_EDITOR_FONT_FAMILY_KEY = "font_family"
UI_EDITOR_INDENT_STYLE_KEY = "indent_style"
UI_EDITOR_INDENT_SIZE_KEY = "indent_size"
UI_EDITOR_DETECT_INDENTATION_FROM_FILE_KEY = "detect_indentation_from_file"
UI_EDITOR_FORMAT_ON_SAVE_KEY = "format_on_save"
UI_EDITOR_TRIM_TRAILING_WHITESPACE_ON_SAVE_KEY = "trim_trailing_whitespace_on_save"
UI_EDITOR_INSERT_FINAL_NEWLINE_ON_SAVE_KEY = "insert_final_newline_on_save"
UI_EDITOR_ENABLE_PREVIEW_KEY = "enable_preview"
UI_EDITOR_AUTO_SAVE_KEY = "auto_save"
UI_EDITOR_TAB_WIDTH_DEFAULT = 4
UI_EDITOR_FONT_SIZE_DEFAULT = 10
UI_EDITOR_FONT_FAMILY_DEFAULT = "monospace"
UI_EDITOR_INDENT_STYLE_DEFAULT = "spaces"
UI_EDITOR_INDENT_SIZE_DEFAULT = 4
UI_EDITOR_DETECT_INDENTATION_FROM_FILE_DEFAULT = True
UI_EDITOR_FORMAT_ON_SAVE_DEFAULT = False
UI_EDITOR_TRIM_TRAILING_WHITESPACE_ON_SAVE_DEFAULT = True
UI_EDITOR_INSERT_FINAL_NEWLINE_ON_SAVE_DEFAULT = True
UI_EDITOR_ENABLE_PREVIEW_DEFAULT = True
UI_EDITOR_AUTO_SAVE_DEFAULT = False
UI_INTELLIGENCE_SETTINGS_KEY = "intelligence"
UI_INTELLIGENCE_ENABLE_COMPLETION_KEY = "enable_completion"
UI_INTELLIGENCE_AUTO_TRIGGER_COMPLETION_KEY = "auto_trigger_completion"
UI_INTELLIGENCE_COMPLETION_MIN_CHARS_KEY = "completion_min_chars"
UI_INTELLIGENCE_ENABLE_DIAGNOSTICS_KEY = "enable_diagnostics"
UI_INTELLIGENCE_DIAGNOSTICS_REALTIME_KEY = "diagnostics_realtime"
UI_INTELLIGENCE_ENABLE_QUICK_FIXES_KEY = "enable_quick_fixes"
UI_INTELLIGENCE_QUICK_FIX_REQUIRE_PREVIEW_FOR_MULTIFILE_KEY = "quick_fix_require_preview_for_multifile"
UI_INTELLIGENCE_ENABLE_COMPLETION_DEFAULT = True
UI_INTELLIGENCE_AUTO_TRIGGER_COMPLETION_DEFAULT = False
UI_INTELLIGENCE_COMPLETION_MIN_CHARS_DEFAULT = 2
UI_INTELLIGENCE_ENABLE_DIAGNOSTICS_DEFAULT = True
UI_INTELLIGENCE_DIAGNOSTICS_REALTIME_DEFAULT = True
UI_INTELLIGENCE_ENABLE_QUICK_FIXES_DEFAULT = True
UI_INTELLIGENCE_QUICK_FIX_REQUIRE_PREVIEW_FOR_MULTIFILE_DEFAULT = True
UI_INTELLIGENCE_CACHE_ENABLED_KEY = "cache_enabled"
UI_INTELLIGENCE_INCREMENTAL_INDEXING_KEY = "incremental_indexing"
UI_INTELLIGENCE_METRICS_LOGGING_ENABLED_KEY = "metrics_logging_enabled"
UI_INTELLIGENCE_FORCE_FULL_REINDEX_ON_OPEN_KEY = "force_full_reindex_on_open"
UI_INTELLIGENCE_HIGHLIGHTING_ADAPTIVE_MODE_KEY = "highlighting_adaptive_mode"
UI_INTELLIGENCE_HIGHLIGHTING_REDUCED_THRESHOLD_CHARS_KEY = "highlighting_reduced_threshold_chars"
UI_INTELLIGENCE_HIGHLIGHTING_LEXICAL_ONLY_THRESHOLD_CHARS_KEY = "highlighting_lexical_only_threshold_chars"
UI_INTELLIGENCE_CACHE_ENABLED_DEFAULT = True
UI_INTELLIGENCE_INCREMENTAL_INDEXING_DEFAULT = True
UI_INTELLIGENCE_METRICS_LOGGING_ENABLED_DEFAULT = True
UI_INTELLIGENCE_FORCE_FULL_REINDEX_ON_OPEN_DEFAULT = False
HIGHLIGHTING_MODE_NORMAL = "normal"
HIGHLIGHTING_MODE_REDUCED = "reduced"
HIGHLIGHTING_MODE_LEXICAL_ONLY = "lexical_only"
UI_INTELLIGENCE_HIGHLIGHTING_ADAPTIVE_MODE_DEFAULT = HIGHLIGHTING_MODE_NORMAL
UI_INTELLIGENCE_HIGHLIGHTING_REDUCED_THRESHOLD_CHARS_DEFAULT = 250_000
UI_INTELLIGENCE_HIGHLIGHTING_LEXICAL_ONLY_THRESHOLD_CHARS_DEFAULT = 600_000
UI_THEME_SETTINGS_KEY = "theme"
UI_THEME_MODE_KEY = "mode"
UI_THEME_MODE_SYSTEM = "system"
UI_THEME_MODE_LIGHT = "light"
UI_THEME_MODE_DARK = "dark"
UI_THEME_MODE_DEFAULT = UI_THEME_MODE_SYSTEM
UI_KEYBINDINGS_SETTINGS_KEY = "keybindings"
UI_KEYBINDINGS_OVERRIDES_KEY = "overrides"
UI_SYNTAX_COLORS_SETTINGS_KEY = "syntax_colors"
UI_SYNTAX_COLORS_LIGHT_KEY = "light"
UI_SYNTAX_COLORS_DARK_KEY = "dark"
UI_LINTER_SETTINGS_KEY = "linter"
UI_LINTER_ENABLED_KEY = "enabled"
UI_LINTER_SELECTED_LINTER_KEY = "selected_linter"
UI_LINTER_RULE_OVERRIDES_KEY = "rule_overrides"
LINTER_PROVIDER_DEFAULT = "default"
LINTER_PROVIDER_PYFLAKES = "pyflakes"
LINTER_PROVIDERS = (LINTER_PROVIDER_DEFAULT, LINTER_PROVIDER_PYFLAKES)
UI_OUTPUT_SETTINGS_KEY = "output"
UI_OUTPUT_AUTO_OPEN_CONSOLE_ON_RUN_OUTPUT_KEY = "auto_open_console_on_run_output"
UI_OUTPUT_AUTO_OPEN_PROBLEMS_ON_RUN_FAILURE_KEY = "auto_open_problems_on_run_failure"
UI_OUTPUT_AUTO_OPEN_CONSOLE_ON_RUN_OUTPUT_DEFAULT = True
UI_OUTPUT_AUTO_OPEN_PROBLEMS_ON_RUN_FAILURE_DEFAULT = True
UI_PLUGINS_SETTINGS_KEY = "plugins"
UI_PLUGINS_SAFE_MODE_KEY = "safe_mode"
UI_PLUGINS_SAFE_MODE_DEFAULT = False
LAST_PROJECT_PATH_KEY = "last_project_path"

UI_FILE_EXCLUDES_SETTINGS_KEY = "file_excludes"
UI_FILE_EXCLUDES_PATTERNS_KEY = "patterns"

PROJECT_META_DIRNAME = "cbcs"
PROJECT_MANIFEST_FILENAME = "project.json"
PROJECT_SETTINGS_FILENAME = "settings.json"
PROJECT_SESSION_FILENAME = "session.json"
PROJECT_RUNS_DIRNAME = "runs"
PROJECT_LOGS_DIRNAME = "logs"
PROJECT_CACHE_DIRNAME = "cache"
PROJECT_SETTINGS_OVERRIDABLE_ROOT_KEYS = (
    UI_EDITOR_SETTINGS_KEY,
    UI_INTELLIGENCE_SETTINGS_KEY,
    UI_LINTER_SETTINGS_KEY,
    UI_FILE_EXCLUDES_SETTINGS_KEY,
    UI_OUTPUT_SETTINGS_KEY,
)
GLOBAL_ONLY_SETTINGS_ROOT_KEYS = (
    UI_THEME_SETTINGS_KEY,
    UI_SYNTAX_COLORS_SETTINGS_KEY,
    UI_KEYBINDINGS_SETTINGS_KEY,
    UI_LAYOUT_SETTINGS_KEY,
    LAST_PROJECT_PATH_KEY,
    UI_IMPORT_UPDATE_POLICY_KEY,
    UI_PLUGINS_SETTINGS_KEY,
)
RUN_MANIFEST_FILENAME_PREFIX = "run_manifest_"
RUN_ID_TIMESTAMP_FORMAT = "%Y%m%d_%H%M%S"
RUN_MANIFEST_VERSION = 1

RUN_EXIT_SUCCESS = 0
RUN_EXIT_USER_CODE_ERROR = 1
RUN_EXIT_BOOTSTRAP_ERROR = 2
RUN_EXIT_INVALID_MANIFEST = 3
RUN_EXIT_TERMINATED_BY_USER = 130
RUN_MODE_PYTHON_SCRIPT = "python_script"
RUN_MODE_PYTHON_REPL = "python_repl"
RUN_MODE_PYTHON_DEBUG = "python_debug"

TEMP_NAMESPACE_DIRNAME = "choreboy_code_studio"
