"""Shared constants for bootstrap/path contracts."""

APP_RUN_PATH = "/opt/freecad/AppRun"

GLOBAL_STATE_DIRNAME = ".choreboy_code_studio"
GLOBAL_SETTINGS_FILENAME = "settings.json"
GLOBAL_RECENT_PROJECTS_FILENAME = "recent_projects.json"
GLOBAL_LOGS_DIRNAME = "logs"
GLOBAL_CACHE_DIRNAME = "cache"
GLOBAL_CRASH_REPORTS_DIRNAME = "crash_reports"
GLOBAL_STATE_DB_FILENAME = "state.sqlite3"
APP_LOG_FILENAME = "app.log"
APP_LOGGER_NAMESPACE = "choreboy_code_studio"
APP_LOG_FORMAT = "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
APP_LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

PROJECT_META_DIRNAME = ".cbcs"
PROJECT_MANIFEST_FILENAME = "project.json"
PROJECT_RUNS_DIRNAME = "runs"
PROJECT_CACHE_DIRNAME = "cache"
PROJECT_LOGS_DIRNAME = "logs"
RUN_MANIFEST_FILENAME_PREFIX = "run_manifest_"
RUN_LOG_FILENAME_PREFIX = "run_"
RUN_LOG_FILENAME_SUFFIX = ".log"
RUN_ID_TIMESTAMP_FORMAT = "%Y%m%d_%H%M%S"
RUN_MANIFEST_VERSION = 1

RUN_EXIT_SUCCESS = 0
RUN_EXIT_USER_CODE_ERROR = 1
RUN_EXIT_BOOTSTRAP_ERROR = 2
RUN_EXIT_INVALID_MANIFEST = 3
RUN_EXIT_SAFE_MODE_BLOCKED = 4
RUN_EXIT_TERMINATED_BY_USER = 130

TEMP_NAMESPACE_DIRNAME = "choreboy_code_studio"
